function out = model
%
% StaticDeviceNoLid.m
%
% Model exported on Sep 30 2026, 17:13 by COMSOL 5.6.0.341.

import com.comsol.model.*
import com.comsol.model.util.*

model = ModelUtil.create('Model');

model.modelPath('/home1/eichenba/Downloads');

model.label('StaticDeviceNoLid.mph');

model.param.set('x_offset', '0[mm]', 'Organoid distance from original placement');
model.param.set('r_org', '0.958E-3[m]', 'organoid radius');
model.param.set('h_org', '3.01[mm]', 'height of organoid base');
model.param.set('c_inlet', '0.186[mol/m^3]', 'O2 Conc in Media (saturated in air)');
model.param.set('c_inc', '1.49[mol/m^3]', 'surface PDMS conc');
model.param.set('D_P', '3.4e-9[m^2/s]', 'Diffusion Constant O2 through PDMS');
model.param.set('V_max', '0.0036[mol/(m^3*s)]', 'Max O2 Consumption Rate (approximation)');
model.param.set('K_m', '0.5e-3[mol/m^3]', 'Michaelis-Menten constant for O3 consumption');
model.param.set('c_hypox', '0.05[mM]', 'concentration of O2 for Hypoxic Tissue');
model.param.set('c_unit', '1[mM]', 'makes heaviside function unitless');
model.param.set('v_spr', '1e-2[m/s]', 'spring speed');
model.param.set('K_p', 'c_inc/c_inlet', 'partition coefficient PDMS:Media');
model.param.set('c_unit1', '1[mM/mm]', 'unit value');
model.param.set('w', '0.01', 'width for flc2hs');

model.component.create('comp3', true);

model.component('comp3').geom.create('geom3', 3);

model.component('comp3').label('Static Device');

model.component('comp3').mesh.create('mesh3');

model.component('comp3').geom('geom3').lengthUnit('mm');
model.component('comp3').geom('geom3').create('wp2', 'WorkPlane');
model.component('comp3').geom('geom3').feature('wp2').set('quickz', 3);
model.component('comp3').geom('geom3').feature('wp2').set('unite', true);
model.component('comp3').geom('geom3').feature('wp2').geom.create('r1', 'Rectangle');
model.component('comp3').geom('geom3').feature('wp2').geom.feature('r1').set('pos', [-4.760972835 -4.760972835]);
model.component('comp3').geom('geom3').feature('wp2').geom.feature('r1').set('size', [9.52194567 9.52194567]);
model.component('comp3').geom('geom3').create('ext2', 'Extrude');
model.component('comp3').geom('geom3').feature('ext2').setIndex('distance', '12', 0);
model.component('comp3').geom('geom3').feature('ext2').setIndex('scale', '1.535747384', 0, 0);
model.component('comp3').geom('geom3').feature('ext2').setIndex('scale', '1.535747384', 0, 1);
model.component('comp3').geom('geom3').feature('ext2').selection('input').set({'wp2'});
model.component('comp3').geom('geom3').create('uni1', 'Union');
model.component('comp3').geom('geom3').feature('uni1').set('intbnd', false);
model.component('comp3').geom('geom3').feature('uni1').selection('input').set({'ext2'});
model.component('comp3').geom('geom3').create('cone1', 'Cone');
model.component('comp3').geom('geom3').feature('cone1').set('pos', [0 2.4 3]);
model.component('comp3').geom('geom3').feature('cone1').set('r', 1.05);
model.component('comp3').geom('geom3').feature('cone1').set('h', 1.5);
model.component('comp3').geom('geom3').feature('cone1').set('ang', 12);
model.component('comp3').geom('geom3').create('cone2', 'Cone');
model.component('comp3').geom('geom3').feature('cone2').set('pos', {'1.72 + x_offset' '1.97' '3'});
model.component('comp3').geom('geom3').feature('cone2').set('axis', [0 0 1]);
model.component('comp3').geom('geom3').feature('cone2').set('r', 0.65);
model.component('comp3').geom('geom3').feature('cone2').set('h', 1.5);
model.component('comp3').geom('geom3').feature('cone2').set('ang', 12);
model.component('comp3').geom('geom3').create('cone3', 'Cone');
model.component('comp3').geom('geom3').feature('cone3').set('pos', {'2.9 + x_offset' '1.34' '3'});
model.component('comp3').geom('geom3').feature('cone3').set('r', 0.66);
model.component('comp3').geom('geom3').feature('cone3').set('h', 1.5);
model.component('comp3').geom('geom3').feature('cone3').set('ang', 12);
model.component('comp3').geom('geom3').create('cone5', 'Cone');
model.component('comp3').geom('geom3').feature('cone5').set('pos', {'0.86 + x_offset' '1.23' '3'});
model.component('comp3').geom('geom3').feature('cone5').set('r', 0.25);
model.component('comp3').geom('geom3').feature('cone5').set('ang', 9);
model.component('comp3').geom('geom3').create('cone6', 'Cone');
model.component('comp3').geom('geom3').feature('cone6').set('pos', {'0.62 + x_offset' '0.62' '3'});
model.component('comp3').geom('geom3').feature('cone6').set('r', 0.25);
model.component('comp3').geom('geom3').feature('cone6').set('ang', 9);
model.component('comp3').geom('geom3').create('cone7', 'Cone');
model.component('comp3').geom('geom3').feature('cone7').set('pos', {'3.64 + x_offset' '0' '3'});
model.component('comp3').geom('geom3').feature('cone7').set('axis', [0 0 1]);
model.component('comp3').geom('geom3').feature('cone7').set('r', 0.835);
model.component('comp3').geom('geom3').feature('cone7').set('h', 1.5);
model.component('comp3').geom('geom3').feature('cone7').set('ang', 12);
model.component('comp3').geom('geom3').create('mir2', 'Mirror');
model.component('comp3').geom('geom3').feature('mir2').set('keep', true);
model.component('comp3').geom('geom3').feature('mir2').set('axis', [0 1 0]);
model.component('comp3').geom('geom3').feature('mir2').selection('input').set({'cone1' 'cone2' 'cone3' 'cone5' 'cone6'});
model.component('comp3').geom('geom3').create('mir3', 'Mirror');
model.component('comp3').geom('geom3').feature('mir3').set('keep', true);
model.component('comp3').geom('geom3').feature('mir3').set('axis', [1 0 0]);
model.component('comp3').geom('geom3').feature('mir3').selection('input').set({'cone2' 'cone3' 'cone5' 'cone6' 'cone7' 'mir2(2)' 'mir2(3)' 'mir2(4)' 'mir2(5)'});
model.component('comp3').geom('geom3').create('dif1', 'Difference');
model.component('comp3').geom('geom3').feature('dif1').selection('input').set({'uni1'});
model.component('comp3').geom('geom3').feature('dif1').selection('input2').set({'cone1' 'cone2' 'cone3' 'cone5' 'cone6' 'cone7' 'mir2' 'mir3'});
model.component('comp3').geom('geom3').create('pyr1', 'Pyramid');
model.component('comp3').geom('geom3').feature('pyr1').set('a', 25);
model.component('comp3').geom('geom3').feature('pyr1').set('b', 25);
model.component('comp3').geom('geom3').feature('pyr1').set('h', 15);
model.component('comp3').geom('geom3').feature('pyr1').set('rat', 0.74493);
model.component('comp3').geom('geom3').create('sph1', 'Sphere');
model.component('comp3').geom('geom3').feature('sph1').set('pos', {'-1.75 - x_offset' '0' 'h_org + r_org'});
model.component('comp3').geom('geom3').feature('sph1').set('r', 'r_org');
model.component('comp3').geom('geom3').create('sph2', 'Sphere');
model.component('comp3').geom('geom3').feature('sph2').set('pos', {'1.75 + x_offset' '0' 'h_org+r_org'});
model.component('comp3').geom('geom3').feature('sph2').set('r', 'r_org');
model.component('comp3').geom('geom3').run;
model.component('comp3').geom('geom3').run('fin');

model.frame('material1').tag('material3');
model.frame('mesh1').tag('mesh3');
model.frame('geometry1').tag('geometry3');
model.frame('spatial1').tag('spatial3');

model.component('comp3').variable.create('var1');
model.component('comp3').variable('var1').set('c', 'c_PDMS');
model.component('comp3').variable('var1').selection.geom('geom3', 3);
model.component('comp3').variable('var1').selection.set([1]);
model.component('comp3').variable.create('var2');
model.component('comp3').variable('var2').set('c', 'c_media');
model.component('comp3').variable('var2').selection.geom('geom3', 3);
model.component('comp3').variable('var2').selection.set([2 3 4]);

model.component('comp3').view('view1').tag('view5');
model.component('comp3').view('view2').tag('view7');
model.component('comp3').view('view5').clip.create('plane1', 'ClipPlane');
model.view.create('view21', 3);
model.view.create('view22', 2);
model.view.create('view23', 2);
model.view.create('view24', 2);
model.view.create('view25', 2);
model.view.create('view28', 2);
model.view.create('view29', 2);

model.component('comp3').material.create('mat2', 'Common');
model.component('comp3').material.create('mat3', 'Common');
model.component('comp3').material.create('mat4', 'Common');
model.component('comp3').material('mat2').selection.set([2]);
model.component('comp3').material('mat2').propertyGroup('def').func.create('eta', 'Piecewise');
model.component('comp3').material('mat2').propertyGroup('def').func.create('Cp', 'Piecewise');
model.component('comp3').material('mat2').propertyGroup('def').func.create('rho', 'Piecewise');
model.component('comp3').material('mat2').propertyGroup('def').func.create('k', 'Piecewise');
model.component('comp3').material('mat2').propertyGroup('def').func.create('cs', 'Interpolation');
model.component('comp3').material('mat2').propertyGroup('def').func.create('an1', 'Analytic');
model.component('comp3').material('mat2').propertyGroup('def').func.create('an2', 'Analytic');
model.component('comp3').material('mat2').propertyGroup('def').func.create('an3', 'Analytic');
model.component('comp3').material('mat3').selection.set([1 3 4]);
model.component('comp3').material('mat4').selection.set([1]);

model.component('comp3').cpl.create('intop1', 'Integration');
model.component('comp3').cpl.create('intop2', 'Integration');
model.component('comp3').cpl.create('genext1', 'GeneralExtrusion');
model.component('comp3').cpl.create('genext2', 'GeneralExtrusion');
model.component('comp3').cpl('intop1').selection.set([3]);
model.component('comp3').cpl('intop2').selection.set([4]);
model.component('comp3').cpl('genext1').selection.set([2]);
model.component('comp3').cpl('genext2').selection.set([1]);

model.component('comp3').coordSystem('sys1').tag('sys3');

model.component('comp3').physics.create('tds', 'DilutedSpecies', 'geom3');
model.component('comp3').physics('tds').field('concentration').field('c_PDMS');
model.component('comp3').physics('tds').field('concentration').component({'c_PDMS'});
model.component('comp3').physics('tds').selection.set([1]);
model.component('comp3').physics('tds').create('conc1', 'Concentration', 2);
model.component('comp3').physics('tds').feature('conc1').selection.set([1 3 4 5 128]);
model.component('comp3').physics('tds').create('cdm3', 'ConvectionDiffusionMigration', 3);
model.component('comp3').physics('tds').feature('cdm3').selection.set([1]);
model.component('comp3').physics('tds').create('fl1', 'FluxBoundary', 2);
model.component('comp3').physics('tds').feature('fl1').selection.set([6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 30 31 32 33 34 35 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 94 95 96 97 98 99 100 101 102 103 104 105 106 107 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127]);
model.component('comp3').physics.create('tds4', 'DilutedSpecies', 'geom3');
model.component('comp3').physics('tds4').identifier('tds4');
model.component('comp3').physics('tds4').field('concentration').field('c_media');
model.component('comp3').physics('tds4').field('concentration').component({'c_media'});
model.component('comp3').physics('tds4').selection.set([2 3 4]);
model.component('comp3').physics('tds4').create('fl1', 'FluxBoundary', 2);
model.component('comp3').physics('tds4').feature('fl1').selection.set([6 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 30 31 32 33 34 35 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 94 95 96 97 98 99 100 101 102 103 104 105 106 107 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127]);
model.component('comp3').physics('tds4').create('reac1', 'Reactions', 3);
model.component('comp3').physics('tds4').feature('reac1').selection.set([3 4]);
model.component('comp3').physics('tds4').create('cdm2', 'ConvectionDiffusionMigration', 3);
model.component('comp3').physics('tds4').feature('cdm2').selection.set([3 4]);
model.component('comp3').physics('tds4').create('conc1', 'Concentration', 2);
model.component('comp3').physics('tds4').feature('conc1').selection.set([7]);
model.component('comp3').physics('tds4').create('sym1', 'Symmetry', 2);

model.component('comp3').mesh('mesh3').create('size1', 'Size');
model.component('comp3').mesh('mesh3').create('size2', 'Size');
model.component('comp3').mesh('mesh3').create('size4', 'Size');
model.component('comp3').mesh('mesh3').create('size3', 'Size');
model.component('comp3').mesh('mesh3').create('cr1', 'CornerRefinement');
model.component('comp3').mesh('mesh3').create('ftet1', 'FreeTet');
model.component('comp3').mesh('mesh3').create('bl1', 'BndLayer');
model.component('comp3').mesh('mesh3').feature('size1').selection.geom('geom3', 3);
model.component('comp3').mesh('mesh3').feature('size1').selection.set([1 2 3 4]);
model.component('comp3').mesh('mesh3').feature('size2').selection.geom('geom3', 3);
model.component('comp3').mesh('mesh3').feature('size4').selection.geom('geom3', 2);
model.component('comp3').mesh('mesh3').feature('size4').selection.set([5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127]);
model.component('comp3').mesh('mesh3').feature('size3').selection.geom('geom3', 1);
model.component('comp3').mesh('mesh3').feature('size3').selection.set([9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284]);
model.component('comp3').mesh('mesh3').feature('cr1').selection.geom('geom3', 3);
model.component('comp3').mesh('mesh3').feature('cr1').selection.set([1 2]);
model.component('comp3').mesh('mesh3').feature('bl1').create('blp', 'BndLayerProp');
model.component('comp3').mesh('mesh3').feature('bl1').feature('blp').selection.set([5 6 7 8]);

model.component('comp3').view('view5').label('Isotropic');
model.component('comp3').view('view5').set('showgrid', false);
model.component('comp3').view('view5').set('transparency', true);
model.component('comp3').view('view5').set('clippingactive', false);
model.component('comp3').view('view5').clip('plane1').set('translationamount', 1.502150039672852);
model.component('comp3').view('view5').clip('plane1').set('position', [10.06538889152916 -1.0216491222381592 5.681511967719814]);
model.component('comp3').view('view5').clip('plane1').set('orientationaxes', [-1.9470718909397888E-7 0 0.9999999999999809; 0 -0.9999999999999996 0; 0.9999999999999809 0 1.9470718909397888E-7]);
model.component('comp3').view('view7').label('View 4');
model.component('comp3').view('view7').axis.set('xmin', -30.893630981445312);
model.component('comp3').view('view7').axis.set('xmax', 30.893630981445312);
model.component('comp3').view('view7').axis.set('ymin', -13.65000057220459);
model.component('comp3').view('view7').axis.set('ymax', 13.65000057220459);
model.view('view21').set('transparency', true);
model.view('view22').axis.set('xmin', -2.83798885345459);
model.view('view22').axis.set('xmax', 3.1019697189331055);
model.view('view22').axis.set('ymin', 0.7920358180999756);
model.view('view22').axis.set('ymax', 8.068485260009766);
model.view('view23').axis.set('xmin', -0.7533961534500122);
model.view('view23').axis.set('xmax', 0.7533961534500122);
model.view('view23').axis.set('ymin', 2.9100003242492676);
model.view('view23').axis.set('ymax', 5.110000133514404);
model.view('view24').axis.set('xmin', -15.165938377380371);
model.view('view24').axis.set('xmax', 15.165938377380371);
model.view('view24').axis.set('ymin', -7.070839881896973);
model.view('view24').axis.set('ymax', 27.070838928222656);
model.view('view25').axis.set('xmin', -12.812405586242676);
model.view('view25').axis.set('xmax', 12.812405586242676);
model.view('view25').axis.set('ymin', -15.695197105407715);
model.view('view25').axis.set('ymax', 15.695197105407715);
model.view('view28').axis.set('xmin', -3.25);
model.view('view28').axis.set('xmax', 2.25);
model.view('view28').axis.set('ymin', -2.828807830810547);
model.view('view28').axis.set('ymax', 3.7971763610839844);
model.view('view29').axis.set('xmin', -3.656132221221924);
model.view('view29').axis.set('xmax', 4.656132221221924);
model.view('view29').axis.set('ymin', -0.25);
model.view('view29').axis.set('ymax', 5.25);

model.component('comp3').material('mat2').label('Water, liquid');
model.component('comp3').material('mat2').set('family', 'water');
model.component('comp3').material('mat2').propertyGroup('def').func('eta').set('arg', 'T');
model.component('comp3').material('mat2').propertyGroup('def').func('eta').set('pieces', {'273.15' '413.15' '1.3799566804-0.021224019151*T^1+1.3604562827E-4*T^2-4.6454090319E-7*T^3+8.9042735735E-10*T^4-9.0790692686E-13*T^5+3.8457331488E-16*T^6'; '413.15' '553.75' '0.00401235783-2.10746715E-5*T^1+3.85772275E-8*T^2-2.39730284E-11*T^3'});
model.component('comp3').material('mat2').propertyGroup('def').func('eta').set('argunit', 'K');
model.component('comp3').material('mat2').propertyGroup('def').func('eta').set('fununit', 'Pa*s');
model.component('comp3').material('mat2').propertyGroup('def').func('Cp').set('arg', 'T');
model.component('comp3').material('mat2').propertyGroup('def').func('Cp').set('pieces', {'273.15' '553.75' '12010.1471-80.4072879*T^1+0.309866854*T^2-5.38186884E-4*T^3+3.62536437E-7*T^4'});
model.component('comp3').material('mat2').propertyGroup('def').func('Cp').set('argunit', 'K');
model.component('comp3').material('mat2').propertyGroup('def').func('Cp').set('fununit', 'J/(kg*K)');
model.component('comp3').material('mat2').propertyGroup('def').func('rho').set('arg', 'T');
model.component('comp3').material('mat2').propertyGroup('def').func('rho').set('smooth', 'contd1');
model.component('comp3').material('mat2').propertyGroup('def').func('rho').set('pieces', {'273.15' '293.15' '0.000063092789034*T^3-0.060367639882855*T^2+18.9229382407066*T-950.704055329848'; '293.15' '373.15' '0.000010335053319*T^3-0.013395065634452*T^2+4.969288832655160*T+432.257114008512'});
model.component('comp3').material('mat2').propertyGroup('def').func('rho').set('argunit', 'K');
model.component('comp3').material('mat2').propertyGroup('def').func('rho').set('fununit', 'kg/m^3');
model.component('comp3').material('mat2').propertyGroup('def').func('k').set('arg', 'T');
model.component('comp3').material('mat2').propertyGroup('def').func('k').set('pieces', {'273.15' '553.75' '-0.869083936+0.00894880345*T^1-1.58366345E-5*T^2+7.97543259E-9*T^3'});
model.component('comp3').material('mat2').propertyGroup('def').func('k').set('argunit', 'K');
model.component('comp3').material('mat2').propertyGroup('def').func('k').set('fununit', 'W/(m*K)');
model.component('comp3').material('mat2').propertyGroup('def').func('cs').set('table', {'273' '1403';  ...
'278' '1427';  ...
'283' '1447';  ...
'293' '1481';  ...
'303' '1507';  ...
'313' '1526';  ...
'323' '1541';  ...
'333' '1552';  ...
'343' '1555';  ...
'353' '1555';  ...
'363' '1550';  ...
'373' '1543'});
model.component('comp3').material('mat2').propertyGroup('def').func('cs').set('interp', 'piecewisecubic');
model.component('comp3').material('mat2').propertyGroup('def').func('cs').set('argunit', 'K');
model.component('comp3').material('mat2').propertyGroup('def').func('cs').set('fununit', 'm/s');
model.component('comp3').material('mat2').propertyGroup('def').func('an1').set('funcname', 'alpha_p');
model.component('comp3').material('mat2').propertyGroup('def').func('an1').set('expr', '-1/rho(T)*d(rho(T),T)');
model.component('comp3').material('mat2').propertyGroup('def').func('an1').set('args', {'T'});
model.component('comp3').material('mat2').propertyGroup('def').func('an1').set('argunit', 'K');
model.component('comp3').material('mat2').propertyGroup('def').func('an1').set('fununit', '1/K');
model.component('comp3').material('mat2').propertyGroup('def').func('an1').set('plotargs', {'T' '273.15' '373.15'});
model.component('comp3').material('mat2').propertyGroup('def').func('an2').set('funcname', 'gamma_w');
model.component('comp3').material('mat2').propertyGroup('def').func('an2').set('expr', '1+(T/Cp(T))*(alpha_p(T)*cs(T))^2');
model.component('comp3').material('mat2').propertyGroup('def').func('an2').set('args', {'T'});
model.component('comp3').material('mat2').propertyGroup('def').func('an2').set('argunit', 'K');
model.component('comp3').material('mat2').propertyGroup('def').func('an2').set('fununit', '1');
model.component('comp3').material('mat2').propertyGroup('def').func('an2').set('plotargs', {'T' '273.15' '373.15'});
model.component('comp3').material('mat2').propertyGroup('def').func('an3').set('funcname', 'muB');
model.component('comp3').material('mat2').propertyGroup('def').func('an3').set('expr', '2.79*eta(T)');
model.component('comp3').material('mat2').propertyGroup('def').func('an3').set('args', {'T'});
model.component('comp3').material('mat2').propertyGroup('def').func('an3').set('argunit', 'K');
model.component('comp3').material('mat2').propertyGroup('def').func('an3').set('fununit', 'Pa*s');
model.component('comp3').material('mat2').propertyGroup('def').func('an3').set('plotargs', {'T' '273.15' '553.75'});
model.component('comp3').material('mat2').propertyGroup('def').set('thermalexpansioncoefficient', '');
model.component('comp3').material('mat2').propertyGroup('def').set('bulkviscosity', '');
model.component('comp3').material('mat2').propertyGroup('def').set('thermalexpansioncoefficient', {'alpha_p(T)' '0' '0' '0' 'alpha_p(T)' '0' '0' '0' 'alpha_p(T)'});
model.component('comp3').material('mat2').propertyGroup('def').set('bulkviscosity', 'muB(T)');
model.component('comp3').material('mat2').propertyGroup('def').set('dynamicviscosity', 'eta(T)');
model.component('comp3').material('mat2').propertyGroup('def').set('ratioofspecificheat', 'gamma_w(T)');
model.component('comp3').material('mat2').propertyGroup('def').set('electricconductivity', {'5.5e-6[S/m]' '0' '0' '0' '5.5e-6[S/m]' '0' '0' '0' '5.5e-6[S/m]'});
model.component('comp3').material('mat2').propertyGroup('def').set('heatcapacity', 'Cp(T)');
model.component('comp3').material('mat2').propertyGroup('def').set('density', 'rho(T)');
model.component('comp3').material('mat2').propertyGroup('def').set('thermalconductivity', {'k(T)' '0' '0' '0' 'k(T)' '0' '0' '0' 'k(T)'});
model.component('comp3').material('mat2').propertyGroup('def').set('soundspeed', 'cs(T)');
model.component('comp3').material('mat2').propertyGroup('def').addInput('temperature');
model.component('comp3').material('mat3').label('Organoid Tissue');
model.component('comp3').material('mat3').propertyGroup('def').set('density', '1050');
model.component('comp3').material('mat3').propertyGroup('def').set('diffusion', {'1.7e-9' '0' '0' '0' '1.7e-9' '0' '0' '0' '1.7e-9'});
model.component('comp3').material('mat3').propertyGroup('def').set('dynamicviscosity', '0.001');
model.component('comp3').material('mat4').label('PDMS');
model.component('comp3').material('mat4').propertyGroup('def').set('density', '1.03[g/cm^3]');
model.component('comp3').material('mat4').propertyGroup('def').set('diffusion', {'D_P' '0' '0' '0' 'D_P' '0' '0' '0' 'D_P'});
model.component('comp3').material('mat4').propertyGroup('def').set('dynamicviscosity', '0');
model.component('comp3').material('mat4').materialType('nonSolid');

model.component('comp3').coordSystem('sys3').label('Boundary System 2');
model.component('comp3').coordSystem('sys3').set('name', 'sys3');

model.component('comp3').physics('tds').label('Oxygen TDS in PDMS');
model.component('comp3').physics('tds').feature('cdm1').set('DiffusionMaterialList', 'mat2');
model.component('comp3').physics('tds').feature('cdm1').set('D_c_PDMS', {'3.0e-9[m^2/s]'; '0'; '0'; '0'; '3.0e-9[m^2/s]'; '0'; '0'; '0'; '3.0e-9[m^2/s]'});
model.component('comp3').physics('tds').feature('init1').set('initc', 'c_inc-0.001');
model.component('comp3').physics('tds').feature('conc1').set('species', true);
model.component('comp3').physics('tds').feature('conc1').set('c0', 'c_inc');
model.component('comp3').physics('tds').feature('cdm3').set('DiffusionMaterialList', 'mat4');
model.component('comp3').physics('tds').feature('cdm3').set('D_c_PDMS', {'D_P'; '0'; '0'; '0'; 'D_P'; '0'; '0'; '0'; 'D_P'});
model.component('comp3').physics('tds').feature('cdm3').label('Transport Properties PDMS');
model.component('comp3').physics('tds').feature('fl1').set('species', true);
model.component('comp3').physics('tds').feature('fl1').set('J0', 'v_spr*(genext1(c_media)-c_PDMS/K_p)');
model.component('comp3').physics('tds').feature('fl1').label('Stiff Spring PDMS Side');
model.component('comp3').physics('tds4').label('Oxygen TDS in Media & Organoids');
model.component('comp3').physics('tds4').feature('cdm1').set('DiffusionMaterialList', 'mat2');
model.component('comp3').physics('tds4').feature('cdm1').set('D_c_media', {'3.4e-9'; '0'; '0'; '0'; '3.4e-9'; '0'; '0'; '0'; '3.4e-9'});
model.component('comp3').physics('tds4').feature('init1').set('initc', 'c_inlet-0.001');
model.component('comp3').physics('tds4').feature('fl1').set('species', true);
model.component('comp3').physics('tds4').feature('fl1').set('J0', 'v_spr*(genext2(c_PDMS)/K_p-c_media)');
model.component('comp3').physics('tds4').feature('fl1').label('Stiff Spring Media Side');
model.component('comp3').physics('tds4').feature('reac1').set('R_c_media', '-(V_max*c)/(c+K_m)*flc2hs(c/c_hypox-1, 0.005)');
model.component('comp3').physics('tds4').feature('cdm2').set('D_c_media', {'3.25e-9[m^2/s]'; '0'; '0'; '0'; '3.25e-9[m^2/s]'; '0'; '0'; '0'; '3.25e-9[m^2/s]'});
model.component('comp3').physics('tds4').feature('cdm2').label('Transport Properties Organoids');
model.component('comp3').physics('tds4').feature('conc1').set('species', true);
model.component('comp3').physics('tds4').feature('conc1').set('c0', 'c_inlet');
model.component('comp3').physics('tds4').feature('sym1').active(false);

model.component('comp3').mesh('mesh3').feature('size1').label('Size 1 General');
model.component('comp3').mesh('mesh3').feature('size1').set('hauto', 3);
model.component('comp3').mesh('mesh3').feature('size1').set('custom', 'on');
model.component('comp3').mesh('mesh3').feature('size1').set('table', 'cfd');
model.component('comp3').mesh('mesh3').feature('size1').set('hmax', 0.5);
model.component('comp3').mesh('mesh3').feature('size1').set('hmaxactive', true);
model.component('comp3').mesh('mesh3').feature('size1').set('hmin', 0.0961);
model.component('comp3').mesh('mesh3').feature('size1').set('hnarrow', 0.9);
model.component('comp3').mesh('mesh3').feature('size1').set('hgrad', 1.5);
model.component('comp3').mesh('mesh3').feature('size1').set('hgradactive', true);
model.component('comp3').mesh('mesh3').feature('size1').set('hminactive', false);
model.component('comp3').mesh('mesh3').feature('size1').set('hcurveactive', false);
model.component('comp3').mesh('mesh3').feature('size1').set('hnarrowactive', false);
model.component('comp3').mesh('mesh3').feature('size2').set('hauto', 1);
model.component('comp3').mesh('mesh3').feature('size4').set('custom', 'on');
model.component('comp3').mesh('mesh3').feature('size4').set('hmax', 0.07);
model.component('comp3').mesh('mesh3').feature('size4').set('hmaxactive', true);
model.component('comp3').mesh('mesh3').feature('size4').set('hmin', 0.52);
model.component('comp3').mesh('mesh3').feature('size4').set('hcurve', 1.5);
model.component('comp3').mesh('mesh3').feature('size4').set('hgradactive', true);
model.component('comp3').mesh('mesh3').feature('size4').set('hminactive', false);
model.component('comp3').mesh('mesh3').feature('size4').set('hcurveactive', false);
model.component('comp3').mesh('mesh3').feature('size3').set('custom', 'on');
model.component('comp3').mesh('mesh3').feature('size3').set('hmax', 0.01);
model.component('comp3').mesh('mesh3').feature('size3').set('hmaxactive', true);
model.component('comp3').mesh('mesh3').feature('size3').set('hmin', 0.52);
model.component('comp3').mesh('mesh3').feature('size3').set('hcurve', 1.5);
model.component('comp3').mesh('mesh3').feature('size3').set('hgradactive', true);
model.component('comp3').mesh('mesh3').feature('size3').set('hminactive', false);
model.component('comp3').mesh('mesh3').feature('size3').set('hcurveactive', false);
model.component('comp3').mesh('mesh3').feature('cr1').selection('boundary').set([5 7 8]);
model.component('comp3').mesh('mesh3').feature('bl1').active(false);
model.component('comp3').mesh('mesh3').feature('bl1').set('sharpcorners', 'trim');
model.component('comp3').mesh('mesh3').feature('bl1').feature('blp').set('inittype', 'blhmin');
model.component('comp3').mesh('mesh3').feature('bl1').feature('blp').set('blhmin', 0.05);
model.component('comp3').mesh('mesh3').run;

model.study.create('std25');
model.study('std25').create('time', 'Transient');
model.study.create('std26');
model.study('std26').create('time', 'Transient');
model.study.create('std30');
model.study('std30').create('stat', 'Stationary');

model.sol.create('sol33');
model.sol('sol33').study('std25');
model.sol('sol33').attach('std25');
model.sol('sol33').create('st1', 'StudyStep');
model.sol('sol33').create('v1', 'Variables');
model.sol('sol33').create('t1', 'Time');
model.sol('sol33').feature('t1').create('se1', 'Segregated');
model.sol('sol33').feature('t1').create('i1', 'Iterative');
model.sol('sol33').feature('t1').create('i2', 'Iterative');
model.sol('sol33').feature('t1').create('d1', 'Direct');
model.sol('sol33').feature('t1').create('d2', 'Direct');
model.sol('sol33').feature('t1').feature('se1').create('ss1', 'SegregatedStep');
model.sol('sol33').feature('t1').feature('se1').create('ss2', 'SegregatedStep');
model.sol('sol33').feature('t1').feature('se1').feature.remove('ssDef');
model.sol('sol33').feature('t1').feature('i1').create('mg1', 'Multigrid');
model.sol('sol33').feature('t1').feature('i1').feature('mg1').feature('pr').create('sl1', 'SORLine');
model.sol('sol33').feature('t1').feature('i1').feature('mg1').feature('po').create('sl1', 'SORLine');
model.sol('sol33').feature('t1').feature('i1').feature('mg1').feature('cs').create('d1', 'Direct');
model.sol('sol33').feature('t1').feature('i2').create('mg1', 'Multigrid');
model.sol('sol33').feature('t1').feature('i2').feature('mg1').feature('pr').create('sl1', 'SORLine');
model.sol('sol33').feature('t1').feature('i2').feature('mg1').feature('po').create('sl1', 'SORLine');
model.sol('sol33').feature('t1').feature('i2').feature('mg1').feature('cs').create('d1', 'Direct');
model.sol('sol33').feature('t1').feature.remove('fcDef');
model.sol.create('sol34');
model.sol('sol34').study('std26');
model.sol('sol34').attach('std26');
model.sol('sol34').create('st1', 'StudyStep');
model.sol('sol34').create('v1', 'Variables');
model.sol('sol34').create('t1', 'Time');
model.sol('sol34').feature('t1').create('se1', 'Segregated');
model.sol('sol34').feature('t1').create('i1', 'Iterative');
model.sol('sol34').feature('t1').create('i2', 'Iterative');
model.sol('sol34').feature('t1').create('d1', 'Direct');
model.sol('sol34').feature('t1').create('d2', 'Direct');
model.sol('sol34').feature('t1').feature('se1').create('ss1', 'SegregatedStep');
model.sol('sol34').feature('t1').feature('se1').create('ss2', 'SegregatedStep');
model.sol('sol34').feature('t1').feature('se1').feature.remove('ssDef');
model.sol('sol34').feature('t1').feature('i1').create('mg1', 'Multigrid');
model.sol('sol34').feature('t1').feature('i1').feature('mg1').feature('pr').create('sl1', 'SORLine');
model.sol('sol34').feature('t1').feature('i1').feature('mg1').feature('po').create('sl1', 'SORLine');
model.sol('sol34').feature('t1').feature('i1').feature('mg1').feature('cs').create('d1', 'Direct');
model.sol('sol34').feature('t1').feature('i2').create('mg1', 'Multigrid');
model.sol('sol34').feature('t1').feature('i2').feature('mg1').feature('pr').create('sl1', 'SORLine');
model.sol('sol34').feature('t1').feature('i2').feature('mg1').feature('po').create('sl1', 'SORLine');
model.sol('sol34').feature('t1').feature('i2').feature('mg1').feature('cs').create('d1', 'Direct');
model.sol('sol34').feature('t1').feature.remove('fcDef');
model.sol.create('sol38');
model.sol('sol38').study('std30');
model.sol('sol38').attach('std30');
model.sol('sol38').create('st1', 'StudyStep');
model.sol('sol38').create('v1', 'Variables');
model.sol('sol38').create('s1', 'Stationary');
model.sol('sol38').feature('s1').create('se1', 'Segregated');
model.sol('sol38').feature('s1').create('i1', 'Iterative');
model.sol('sol38').feature('s1').create('i2', 'Iterative');
model.sol('sol38').feature('s1').create('d1', 'Direct');
model.sol('sol38').feature('s1').create('d2', 'Direct');
model.sol('sol38').feature('s1').feature('se1').create('ss1', 'SegregatedStep');
model.sol('sol38').feature('s1').feature('se1').create('ss2', 'SegregatedStep');
model.sol('sol38').feature('s1').feature('se1').feature.remove('ssDef');
model.sol('sol38').feature('s1').feature('i1').create('mg1', 'Multigrid');
model.sol('sol38').feature('s1').feature('i1').feature('mg1').feature('pr').create('sl1', 'SORLine');
model.sol('sol38').feature('s1').feature('i1').feature('mg1').feature('po').create('sl1', 'SORLine');
model.sol('sol38').feature('s1').feature('i1').feature('mg1').feature('cs').create('d1', 'Direct');
model.sol('sol38').feature('s1').feature('i2').create('mg1', 'Multigrid');
model.sol('sol38').feature('s1').feature('i2').feature('mg1').feature('pr').create('sl1', 'SORLine');
model.sol('sol38').feature('s1').feature('i2').feature('mg1').feature('po').create('sl1', 'SORLine');
model.sol('sol38').feature('s1').feature('i2').feature('mg1').feature('cs').create('d1', 'Direct');
model.sol('sol38').feature('s1').feature.remove('fcDef');

model.result.dataset.create('dset5', 'Solution');
model.result.dataset.create('dset6', 'Solution');
model.result.dataset.create('dset10', 'Solution');
model.result.dataset.create('cln2', 'CutLine3D');
model.result.dataset.create('cln3', 'CutLine3D');
model.result.dataset.create('cln4', 'CutLine3D');
model.result.dataset('dset6').set('solution', 'sol34');
model.result.dataset('dset10').set('solution', 'sol38');
model.result.dataset('cln2').set('data', 'dset10');
model.result.dataset('cln3').set('data', 'dset10');
model.result.dataset('cln4').set('data', 'dset10');
model.result.dataset.remove('dset1');
model.result.dataset.remove('dset2');
model.result.dataset.remove('dset3');
model.result.numerical.create('int1', 'IntSurface');
model.result.numerical.create('gev1', 'EvalGlobal');
model.result.numerical('int1').set('data', 'dset10');
model.result.numerical('int1').selection.set([6 8 10 11 13 14 16 17 20 22 23 30 31 34 40 41 44 45 48 49 52 54 55 58 59 62 64 66 67]);
model.result.numerical('int1').set('probetag', 'none');
model.result.numerical('gev1').set('data', 'dset10');
model.result.numerical('gev1').set('probetag', 'none');
model.result.create('pg4', 'PlotGroup3D');
model.result.create('pg19', 'PlotGroup1D');
model.result.create('pg20', 'PlotGroup1D');
model.result.create('pg23', 'PlotGroup3D');
model.result.create('pg24', 'PlotGroup3D');
model.result('pg4').set('data', 'dset6');
model.result('pg4').create('slc1', 'Slice');
model.result('pg4').create('slc2', 'Slice');
model.result('pg4').feature('slc2').set('expr', 'c_media');
model.result('pg19').create('lngr1', 'LineGraph');
model.result('pg19').create('lngr2', 'LineGraph');
model.result('pg19').create('lngr3', 'LineGraph');
model.result('pg19').feature('lngr1').set('expr', 'c');
model.result('pg19').feature('lngr2').set('expr', 'c');
model.result('pg19').feature('lngr3').set('expr', 'c');
model.result('pg20').create('lngr1', 'LineGraph');
model.result('pg20').create('lngr2', 'LineGraph');
model.result('pg20').feature('lngr1').set('expr', 'flc2hs(c/c_hypox-1,0.5)');
model.result('pg20').feature('lngr2').set('expr', 'c');
model.result('pg23').set('data', 'dset10');
model.result('pg23').create('str1', 'Streamline');
model.result('pg23').create('str2', 'Streamline');
model.result('pg23').feature('str1').create('col', 'Color');
model.result('pg23').feature('str1').feature('col').set('expr', 'c_media');
model.result('pg23').feature('str2').set('data', 'dset10');
model.result('pg23').feature('str2').create('col', 'Color');
model.result('pg24').set('data', 'dset10');
model.result('pg24').selection.geom('geom3', 3);
model.result('pg24').selection.set([3]);
model.result('pg24').create('slc1', 'Slice');
model.result('pg24').feature('slc1').set('expr', 'c_media');
model.result.export.create('img3', 'Image');
model.result.export.create('img4', 'Image');
model.result.export.create('data1', 'Data');
model.result.export.create('data2', 'Data');
model.result.export.create('data3', 'Data');
model.result.export.create('img5', 'Image');
model.result.export.create('img6', 'Image');

model.study('std25').label('Timestep 0 0.001 0.01');
model.study('std25').feature('time').set('tlist', '0, 0.001, 0.01');
model.study('std26').label('Timestep Up to 1 min');
model.study('std26').feature('time').set('tlist', '0.01, 0.1, 1, 0.1[min], 1[min]');
model.study('std26').feature('time').set('useinitsol', true);
model.study('std26').feature('time').set('initmethod', 'sol');
model.study('std26').feature('time').set('initstudy', 'std25');
model.study('std26').feature('time').set('solnum', 'last');
model.study('std30').label('Stationary');
model.study('std30').feature('stat').set('useinitsol', true);
model.study('std30').feature('stat').set('initmethod', 'sol');
model.study('std30').feature('stat').set('initstudy', 'std26');
model.study('std30').feature('stat').set('solnum', 'last');

model.sol('sol33').attach('std25');
model.sol('sol33').feature('st1').label('Compile Equations: Time Dependent');
model.sol('sol33').feature('v1').label('Dependent Variables 1.1');
model.sol('sol33').feature('v1').set('clist', {'0, 0.001, 0.01' '1.0E-5[s]'});
model.sol('sol33').feature('t1').label('Time-Dependent Solver 1.1');
model.sol('sol33').feature('t1').set('control', 'user');
model.sol('sol33').feature('t1').set('tlist', '0, 0.001, 0.01');
model.sol('sol33').feature('t1').set('rtol', 0.005);
model.sol('sol33').feature('t1').set('maxorder', 2);
model.sol('sol33').feature('t1').set('stabcntrl', true);
model.sol('sol33').feature('t1').feature('dDef').label('Direct 3');
model.sol('sol33').feature('t1').feature('aDef').label('Advanced 1');
model.sol('sol33').feature('t1').feature('aDef').set('cachepattern', true);
model.sol('sol33').feature('t1').feature('se1').label('Segregated 1.1');
model.sol('sol33').feature('t1').feature('se1').set('segstabacc', 'segaacc');
model.sol('sol33').feature('t1').feature('se1').set('segaaccdim', 5);
model.sol('sol33').feature('t1').feature('se1').set('segaaccmix', 0.9);
model.sol('sol33').feature('t1').feature('se1').set('segaaccdelay', 1);
model.sol('sol33').feature('t1').feature('se1').feature('ss1').label('Concentration c_PDMS');
model.sol('sol33').feature('t1').feature('se1').feature('ss1').set('linsolver', 'i1');
model.sol('sol33').feature('t1').feature('se1').feature('ss1').set('subdamp', 0.8);
model.sol('sol33').feature('t1').feature('se1').feature('ss1').set('subjtech', 'once');
model.sol('sol33').feature('t1').feature('se1').feature('ss2').label('Concentration c_media');
model.sol('sol33').feature('t1').feature('se1').feature('ss2').set('linsolver', 'i2');
model.sol('sol33').feature('t1').feature('se1').feature('ss2').set('subdamp', 0.8);
model.sol('sol33').feature('t1').feature('se1').feature('ss2').set('subjtech', 'once');
model.sol('sol33').feature('t1').feature('i1').label('AMG, concentrations (tds)');
model.sol('sol33').feature('t1').feature('i1').set('maxlinit', 50);
model.sol('sol33').feature('t1').feature('i1').feature('ilDef').label('Incomplete LU 1');
model.sol('sol33').feature('t1').feature('i1').feature('mg1').label('Multigrid 1.1');
model.sol('sol33').feature('t1').feature('i1').feature('mg1').set('prefun', 'saamg');
model.sol('sol33').feature('t1').feature('i1').feature('mg1').set('maxcoarsedof', 50000);
model.sol('sol33').feature('t1').feature('i1').feature('mg1').set('saamgcompwise', true);
model.sol('sol33').feature('t1').feature('i1').feature('mg1').set('usesmooth', false);
model.sol('sol33').feature('t1').feature('i1').feature('mg1').feature('pr').label('Presmoother 1');
model.sol('sol33').feature('t1').feature('i1').feature('mg1').feature('pr').feature('soDef').label('SOR 1');
model.sol('sol33').feature('t1').feature('i1').feature('mg1').feature('pr').feature('sl1').label('SOR Line 1.1');
model.sol('sol33').feature('t1').feature('i1').feature('mg1').feature('pr').feature('sl1').set('linesweeptype', 'ssor');
model.sol('sol33').feature('t1').feature('i1').feature('mg1').feature('pr').feature('sl1').set('iter', 1);
model.sol('sol33').feature('t1').feature('i1').feature('mg1').feature('pr').feature('sl1').set('linerelax', 0.7);
model.sol('sol33').feature('t1').feature('i1').feature('mg1').feature('pr').feature('sl1').set('relax', 0.5);
model.sol('sol33').feature('t1').feature('i1').feature('mg1').feature('po').label('Postsmoother 1');
model.sol('sol33').feature('t1').feature('i1').feature('mg1').feature('po').feature('soDef').label('SOR 1');
model.sol('sol33').feature('t1').feature('i1').feature('mg1').feature('po').feature('sl1').label('SOR Line 1.1');
model.sol('sol33').feature('t1').feature('i1').feature('mg1').feature('po').feature('sl1').set('linesweeptype', 'ssor');
model.sol('sol33').feature('t1').feature('i1').feature('mg1').feature('po').feature('sl1').set('iter', 1);
model.sol('sol33').feature('t1').feature('i1').feature('mg1').feature('po').feature('sl1').set('linerelax', 0.7);
model.sol('sol33').feature('t1').feature('i1').feature('mg1').feature('po').feature('sl1').set('relax', 0.5);
model.sol('sol33').feature('t1').feature('i1').feature('mg1').feature('cs').label('Coarse Solver 1');
model.sol('sol33').feature('t1').feature('i1').feature('mg1').feature('cs').feature('dDef').label('Direct 2');
model.sol('sol33').feature('t1').feature('i1').feature('mg1').feature('cs').feature('d1').label('Direct 1.1');
model.sol('sol33').feature('t1').feature('i1').feature('mg1').feature('cs').feature('d1').set('linsolver', 'pardiso');
model.sol('sol33').feature('t1').feature('i1').feature('mg1').feature('cs').feature('d1').set('pivotperturb', 1.0E-13);
model.sol('sol33').feature('t1').feature('i2').label('AMG, concentrations (tds4)');
model.sol('sol33').feature('t1').feature('i2').set('maxlinit', 50);
model.sol('sol33').feature('t1').feature('i2').feature('ilDef').label('Incomplete LU 1');
model.sol('sol33').feature('t1').feature('i2').feature('mg1').label('Multigrid 1.1');
model.sol('sol33').feature('t1').feature('i2').feature('mg1').set('prefun', 'saamg');
model.sol('sol33').feature('t1').feature('i2').feature('mg1').set('maxcoarsedof', 50000);
model.sol('sol33').feature('t1').feature('i2').feature('mg1').set('saamgcompwise', true);
model.sol('sol33').feature('t1').feature('i2').feature('mg1').set('usesmooth', false);
model.sol('sol33').feature('t1').feature('i2').feature('mg1').feature('pr').label('Presmoother 1');
model.sol('sol33').feature('t1').feature('i2').feature('mg1').feature('pr').feature('soDef').label('SOR 1');
model.sol('sol33').feature('t1').feature('i2').feature('mg1').feature('pr').feature('sl1').label('SOR Line 1.1');
model.sol('sol33').feature('t1').feature('i2').feature('mg1').feature('pr').feature('sl1').set('linesweeptype', 'ssor');
model.sol('sol33').feature('t1').feature('i2').feature('mg1').feature('pr').feature('sl1').set('iter', 1);
model.sol('sol33').feature('t1').feature('i2').feature('mg1').feature('pr').feature('sl1').set('linerelax', 0.7);
model.sol('sol33').feature('t1').feature('i2').feature('mg1').feature('pr').feature('sl1').set('relax', 0.5);
model.sol('sol33').feature('t1').feature('i2').feature('mg1').feature('po').label('Postsmoother 1');
model.sol('sol33').feature('t1').feature('i2').feature('mg1').feature('po').feature('soDef').label('SOR 1');
model.sol('sol33').feature('t1').feature('i2').feature('mg1').feature('po').feature('sl1').label('SOR Line 1.1');
model.sol('sol33').feature('t1').feature('i2').feature('mg1').feature('po').feature('sl1').set('linesweeptype', 'ssor');
model.sol('sol33').feature('t1').feature('i2').feature('mg1').feature('po').feature('sl1').set('iter', 1);
model.sol('sol33').feature('t1').feature('i2').feature('mg1').feature('po').feature('sl1').set('linerelax', 0.7);
model.sol('sol33').feature('t1').feature('i2').feature('mg1').feature('po').feature('sl1').set('relax', 0.5);
model.sol('sol33').feature('t1').feature('i2').feature('mg1').feature('cs').label('Coarse Solver 1');
model.sol('sol33').feature('t1').feature('i2').feature('mg1').feature('cs').feature('dDef').label('Direct 2');
model.sol('sol33').feature('t1').feature('i2').feature('mg1').feature('cs').feature('d1').label('Direct 1.1');
model.sol('sol33').feature('t1').feature('i2').feature('mg1').feature('cs').feature('d1').set('linsolver', 'pardiso');
model.sol('sol33').feature('t1').feature('i2').feature('mg1').feature('cs').feature('d1').set('pivotperturb', 1.0E-13);
model.sol('sol33').feature('t1').feature('d1').label('Direct, concentrations (tds)');
model.sol('sol33').feature('t1').feature('d1').set('linsolver', 'pardiso');
model.sol('sol33').feature('t1').feature('d1').set('pivotperturb', 1.0E-13);
model.sol('sol33').feature('t1').feature('d2').label('Direct, concentrations (tds4)');
model.sol('sol33').feature('t1').feature('d2').set('linsolver', 'pardiso');
model.sol('sol33').feature('t1').feature('d2').set('pivotperturb', 1.0E-13);
model.sol('sol33').runAll;
model.sol('sol34').attach('std26');
model.sol('sol34').feature('st1').label('Compile Equations: Time Dependent');
model.sol('sol34').feature('v1').label('Dependent Variables 1.1');
model.sol('sol34').feature('v1').set('initmethod', 'sol');
model.sol('sol34').feature('v1').set('initsol', 'sol33');
model.sol('sol34').feature('v1').set('solnum', 'last');
model.sol('sol34').feature('v1').set('clist', {'0.01, 0.1, 1, 0.1[min], 1[min]' '0.05999[s]'});
model.sol('sol34').feature('t1').label('Time-Dependent Solver 1.1');
model.sol('sol34').feature('t1').set('control', 'user');
model.sol('sol34').feature('t1').set('tlist', '0.01, 0.1, 1, 0.1[min], 1[min]');
model.sol('sol34').feature('t1').set('rtol', 0.005);
model.sol('sol34').feature('t1').set('maxorder', 2);
model.sol('sol34').feature('t1').set('stabcntrl', true);
model.sol('sol34').feature('t1').feature('dDef').label('Direct 3');
model.sol('sol34').feature('t1').feature('aDef').label('Advanced 1');
model.sol('sol34').feature('t1').feature('aDef').set('cachepattern', true);
model.sol('sol34').feature('t1').feature('se1').label('Segregated 1.1');
model.sol('sol34').feature('t1').feature('se1').set('segstabacc', 'segaacc');
model.sol('sol34').feature('t1').feature('se1').set('segaaccdim', 5);
model.sol('sol34').feature('t1').feature('se1').set('segaaccmix', 0.9);
model.sol('sol34').feature('t1').feature('se1').set('segaaccdelay', 1);
model.sol('sol34').feature('t1').feature('se1').feature('ss1').label('Concentration c_PDMS');
model.sol('sol34').feature('t1').feature('se1').feature('ss1').set('linsolver', 'i1');
model.sol('sol34').feature('t1').feature('se1').feature('ss1').set('subdamp', 0.8);
model.sol('sol34').feature('t1').feature('se1').feature('ss1').set('subjtech', 'once');
model.sol('sol34').feature('t1').feature('se1').feature('ss2').label('Concentration c_media');
model.sol('sol34').feature('t1').feature('se1').feature('ss2').set('linsolver', 'i2');
model.sol('sol34').feature('t1').feature('se1').feature('ss2').set('subdamp', 0.8);
model.sol('sol34').feature('t1').feature('se1').feature('ss2').set('subjtech', 'once');
model.sol('sol34').feature('t1').feature('i1').label('AMG, concentrations (tds)');
model.sol('sol34').feature('t1').feature('i1').set('maxlinit', 50);
model.sol('sol34').feature('t1').feature('i1').feature('ilDef').label('Incomplete LU 1');
model.sol('sol34').feature('t1').feature('i1').feature('mg1').label('Multigrid 1.1');
model.sol('sol34').feature('t1').feature('i1').feature('mg1').set('prefun', 'saamg');
model.sol('sol34').feature('t1').feature('i1').feature('mg1').set('maxcoarsedof', 50000);
model.sol('sol34').feature('t1').feature('i1').feature('mg1').set('saamgcompwise', true);
model.sol('sol34').feature('t1').feature('i1').feature('mg1').set('usesmooth', false);
model.sol('sol34').feature('t1').feature('i1').feature('mg1').feature('pr').label('Presmoother 1');
model.sol('sol34').feature('t1').feature('i1').feature('mg1').feature('pr').feature('soDef').label('SOR 1');
model.sol('sol34').feature('t1').feature('i1').feature('mg1').feature('pr').feature('sl1').label('SOR Line 1.1');
model.sol('sol34').feature('t1').feature('i1').feature('mg1').feature('pr').feature('sl1').set('linesweeptype', 'ssor');
model.sol('sol34').feature('t1').feature('i1').feature('mg1').feature('pr').feature('sl1').set('iter', 1);
model.sol('sol34').feature('t1').feature('i1').feature('mg1').feature('pr').feature('sl1').set('linerelax', 0.7);
model.sol('sol34').feature('t1').feature('i1').feature('mg1').feature('pr').feature('sl1').set('relax', 0.5);
model.sol('sol34').feature('t1').feature('i1').feature('mg1').feature('po').label('Postsmoother 1');
model.sol('sol34').feature('t1').feature('i1').feature('mg1').feature('po').feature('soDef').label('SOR 1');
model.sol('sol34').feature('t1').feature('i1').feature('mg1').feature('po').feature('sl1').label('SOR Line 1.1');
model.sol('sol34').feature('t1').feature('i1').feature('mg1').feature('po').feature('sl1').set('linesweeptype', 'ssor');
model.sol('sol34').feature('t1').feature('i1').feature('mg1').feature('po').feature('sl1').set('iter', 1);
model.sol('sol34').feature('t1').feature('i1').feature('mg1').feature('po').feature('sl1').set('linerelax', 0.7);
model.sol('sol34').feature('t1').feature('i1').feature('mg1').feature('po').feature('sl1').set('relax', 0.5);
model.sol('sol34').feature('t1').feature('i1').feature('mg1').feature('cs').label('Coarse Solver 1');
model.sol('sol34').feature('t1').feature('i1').feature('mg1').feature('cs').feature('dDef').label('Direct 2');
model.sol('sol34').feature('t1').feature('i1').feature('mg1').feature('cs').feature('d1').label('Direct 1.1');
model.sol('sol34').feature('t1').feature('i1').feature('mg1').feature('cs').feature('d1').set('linsolver', 'pardiso');
model.sol('sol34').feature('t1').feature('i1').feature('mg1').feature('cs').feature('d1').set('pivotperturb', 1.0E-13);
model.sol('sol34').feature('t1').feature('i2').label('AMG, concentrations (tds4)');
model.sol('sol34').feature('t1').feature('i2').set('maxlinit', 50);
model.sol('sol34').feature('t1').feature('i2').feature('ilDef').label('Incomplete LU 1');
model.sol('sol34').feature('t1').feature('i2').feature('mg1').label('Multigrid 1.1');
model.sol('sol34').feature('t1').feature('i2').feature('mg1').set('prefun', 'saamg');
model.sol('sol34').feature('t1').feature('i2').feature('mg1').set('maxcoarsedof', 50000);
model.sol('sol34').feature('t1').feature('i2').feature('mg1').set('saamgcompwise', true);
model.sol('sol34').feature('t1').feature('i2').feature('mg1').set('usesmooth', false);
model.sol('sol34').feature('t1').feature('i2').feature('mg1').feature('pr').label('Presmoother 1');
model.sol('sol34').feature('t1').feature('i2').feature('mg1').feature('pr').feature('soDef').label('SOR 1');
model.sol('sol34').feature('t1').feature('i2').feature('mg1').feature('pr').feature('sl1').label('SOR Line 1.1');
model.sol('sol34').feature('t1').feature('i2').feature('mg1').feature('pr').feature('sl1').set('linesweeptype', 'ssor');
model.sol('sol34').feature('t1').feature('i2').feature('mg1').feature('pr').feature('sl1').set('iter', 1);
model.sol('sol34').feature('t1').feature('i2').feature('mg1').feature('pr').feature('sl1').set('linerelax', 0.7);
model.sol('sol34').feature('t1').feature('i2').feature('mg1').feature('pr').feature('sl1').set('relax', 0.5);
model.sol('sol34').feature('t1').feature('i2').feature('mg1').feature('po').label('Postsmoother 1');
model.sol('sol34').feature('t1').feature('i2').feature('mg1').feature('po').feature('soDef').label('SOR 1');
model.sol('sol34').feature('t1').feature('i2').feature('mg1').feature('po').feature('sl1').label('SOR Line 1.1');
model.sol('sol34').feature('t1').feature('i2').feature('mg1').feature('po').feature('sl1').set('linesweeptype', 'ssor');
model.sol('sol34').feature('t1').feature('i2').feature('mg1').feature('po').feature('sl1').set('iter', 1);
model.sol('sol34').feature('t1').feature('i2').feature('mg1').feature('po').feature('sl1').set('linerelax', 0.7);
model.sol('sol34').feature('t1').feature('i2').feature('mg1').feature('po').feature('sl1').set('relax', 0.5);
model.sol('sol34').feature('t1').feature('i2').feature('mg1').feature('cs').label('Coarse Solver 1');
model.sol('sol34').feature('t1').feature('i2').feature('mg1').feature('cs').feature('dDef').label('Direct 2');
model.sol('sol34').feature('t1').feature('i2').feature('mg1').feature('cs').feature('d1').label('Direct 1.1');
model.sol('sol34').feature('t1').feature('i2').feature('mg1').feature('cs').feature('d1').set('linsolver', 'pardiso');
model.sol('sol34').feature('t1').feature('i2').feature('mg1').feature('cs').feature('d1').set('pivotperturb', 1.0E-13);
model.sol('sol34').feature('t1').feature('d1').label('Direct, concentrations (tds)');
model.sol('sol34').feature('t1').feature('d1').set('linsolver', 'pardiso');
model.sol('sol34').feature('t1').feature('d1').set('pivotperturb', 1.0E-13);
model.sol('sol34').feature('t1').feature('d2').label('Direct, concentrations (tds4)');
model.sol('sol34').feature('t1').feature('d2').set('linsolver', 'pardiso');
model.sol('sol34').feature('t1').feature('d2').set('pivotperturb', 1.0E-13);
model.sol('sol34').runAll;
model.sol('sol38').attach('std30');
model.sol('sol38').feature('st1').label('Compile Equations: Stationary');
model.sol('sol38').feature('v1').label('Dependent Variables 1.1');
model.sol('sol38').feature('v1').set('initmethod', 'sol');
model.sol('sol38').feature('v1').set('initsol', 'sol34');
model.sol('sol38').feature('v1').set('solnum', 'last');
model.sol('sol38').feature('s1').label('Stationary Solver 1.1');
model.sol('sol38').feature('s1').feature('dDef').label('Direct 3');
model.sol('sol38').feature('s1').feature('aDef').label('Advanced 1');
model.sol('sol38').feature('s1').feature('aDef').set('cachepattern', true);
model.sol('sol38').feature('s1').feature('se1').label('Segregated 1.1');
model.sol('sol38').feature('s1').feature('se1').feature('ss1').label('Concentration c_PDMS');
model.sol('sol38').feature('s1').feature('se1').feature('ss1').set('linsolver', 'i1');
model.sol('sol38').feature('s1').feature('se1').feature('ss1').set('subdamp', 0.35);
model.sol('sol38').feature('s1').feature('se1').feature('ss1').set('subtermconst', 'itertol');
model.sol('sol38').feature('s1').feature('se1').feature('ss1').set('subiter', 3);
model.sol('sol38').feature('s1').feature('se1').feature('ss1').set('subntolfact', 1);
model.sol('sol38').feature('s1').feature('se1').feature('ss2').label('Concentration c_media');
model.sol('sol38').feature('s1').feature('se1').feature('ss2').set('linsolver', 'i2');
model.sol('sol38').feature('s1').feature('se1').feature('ss2').set('subdamp', 0.35);
model.sol('sol38').feature('s1').feature('se1').feature('ss2').set('subtermconst', 'itertol');
model.sol('sol38').feature('s1').feature('se1').feature('ss2').set('subiter', 3);
model.sol('sol38').feature('s1').feature('se1').feature('ss2').set('subntolfact', 1);
model.sol('sol38').feature('s1').feature('i1').label('AMG, concentrations (tds)');
model.sol('sol38').feature('s1').feature('i1').set('nlinnormuse', true);
model.sol('sol38').feature('s1').feature('i1').set('maxlinit', 1000);
model.sol('sol38').feature('s1').feature('i1').feature('ilDef').label('Incomplete LU 1');
model.sol('sol38').feature('s1').feature('i1').feature('mg1').label('Multigrid 1.1');
model.sol('sol38').feature('s1').feature('i1').feature('mg1').set('prefun', 'saamg');
model.sol('sol38').feature('s1').feature('i1').feature('mg1').set('maxcoarsedof', 50000);
model.sol('sol38').feature('s1').feature('i1').feature('mg1').set('saamgcompwise', true);
model.sol('sol38').feature('s1').feature('i1').feature('mg1').set('usesmooth', false);
model.sol('sol38').feature('s1').feature('i1').feature('mg1').feature('pr').label('Presmoother 1');
model.sol('sol38').feature('s1').feature('i1').feature('mg1').feature('pr').feature('soDef').label('SOR 1');
model.sol('sol38').feature('s1').feature('i1').feature('mg1').feature('pr').feature('sl1').label('SOR Line 1.1');
model.sol('sol38').feature('s1').feature('i1').feature('mg1').feature('pr').feature('sl1').set('linesweeptype', 'ssor');
model.sol('sol38').feature('s1').feature('i1').feature('mg1').feature('pr').feature('sl1').set('iter', 1);
model.sol('sol38').feature('s1').feature('i1').feature('mg1').feature('pr').feature('sl1').set('linerelax', 0.7);
model.sol('sol38').feature('s1').feature('i1').feature('mg1').feature('pr').feature('sl1').set('relax', 0.5);
model.sol('sol38').feature('s1').feature('i1').feature('mg1').feature('po').label('Postsmoother 1');
model.sol('sol38').feature('s1').feature('i1').feature('mg1').feature('po').feature('soDef').label('SOR 1');
model.sol('sol38').feature('s1').feature('i1').feature('mg1').feature('po').feature('sl1').label('SOR Line 1.1');
model.sol('sol38').feature('s1').feature('i1').feature('mg1').feature('po').feature('sl1').set('linesweeptype', 'ssor');
model.sol('sol38').feature('s1').feature('i1').feature('mg1').feature('po').feature('sl1').set('iter', 1);
model.sol('sol38').feature('s1').feature('i1').feature('mg1').feature('po').feature('sl1').set('linerelax', 0.7);
model.sol('sol38').feature('s1').feature('i1').feature('mg1').feature('po').feature('sl1').set('relax', 0.5);
model.sol('sol38').feature('s1').feature('i1').feature('mg1').feature('cs').label('Coarse Solver 1');
model.sol('sol38').feature('s1').feature('i1').feature('mg1').feature('cs').feature('dDef').label('Direct 2');
model.sol('sol38').feature('s1').feature('i1').feature('mg1').feature('cs').feature('d1').label('Direct 1.1');
model.sol('sol38').feature('s1').feature('i1').feature('mg1').feature('cs').feature('d1').set('linsolver', 'pardiso');
model.sol('sol38').feature('s1').feature('i1').feature('mg1').feature('cs').feature('d1').set('pivotperturb', 1.0E-13);
model.sol('sol38').feature('s1').feature('i2').label('AMG, concentrations (tds4)');
model.sol('sol38').feature('s1').feature('i2').set('nlinnormuse', true);
model.sol('sol38').feature('s1').feature('i2').set('maxlinit', 1000);
model.sol('sol38').feature('s1').feature('i2').feature('ilDef').label('Incomplete LU 1');
model.sol('sol38').feature('s1').feature('i2').feature('mg1').label('Multigrid 1.1');
model.sol('sol38').feature('s1').feature('i2').feature('mg1').set('prefun', 'saamg');
model.sol('sol38').feature('s1').feature('i2').feature('mg1').set('maxcoarsedof', 50000);
model.sol('sol38').feature('s1').feature('i2').feature('mg1').set('saamgcompwise', true);
model.sol('sol38').feature('s1').feature('i2').feature('mg1').set('usesmooth', false);
model.sol('sol38').feature('s1').feature('i2').feature('mg1').feature('pr').label('Presmoother 1');
model.sol('sol38').feature('s1').feature('i2').feature('mg1').feature('pr').feature('soDef').label('SOR 1');
model.sol('sol38').feature('s1').feature('i2').feature('mg1').feature('pr').feature('sl1').label('SOR Line 1.1');
model.sol('sol38').feature('s1').feature('i2').feature('mg1').feature('pr').feature('sl1').set('linesweeptype', 'ssor');
model.sol('sol38').feature('s1').feature('i2').feature('mg1').feature('pr').feature('sl1').set('iter', 1);
model.sol('sol38').feature('s1').feature('i2').feature('mg1').feature('pr').feature('sl1').set('linerelax', 0.7);
model.sol('sol38').feature('s1').feature('i2').feature('mg1').feature('pr').feature('sl1').set('relax', 0.5);
model.sol('sol38').feature('s1').feature('i2').feature('mg1').feature('po').label('Postsmoother 1');
model.sol('sol38').feature('s1').feature('i2').feature('mg1').feature('po').feature('soDef').label('SOR 1');
model.sol('sol38').feature('s1').feature('i2').feature('mg1').feature('po').feature('sl1').label('SOR Line 1.1');
model.sol('sol38').feature('s1').feature('i2').feature('mg1').feature('po').feature('sl1').set('linesweeptype', 'ssor');
model.sol('sol38').feature('s1').feature('i2').feature('mg1').feature('po').feature('sl1').set('iter', 1);
model.sol('sol38').feature('s1').feature('i2').feature('mg1').feature('po').feature('sl1').set('linerelax', 0.7);
model.sol('sol38').feature('s1').feature('i2').feature('mg1').feature('po').feature('sl1').set('relax', 0.5);
model.sol('sol38').feature('s1').feature('i2').feature('mg1').feature('cs').label('Coarse Solver 1');
model.sol('sol38').feature('s1').feature('i2').feature('mg1').feature('cs').feature('dDef').label('Direct 2');
model.sol('sol38').feature('s1').feature('i2').feature('mg1').feature('cs').feature('d1').label('Direct 1.1');
model.sol('sol38').feature('s1').feature('i2').feature('mg1').feature('cs').feature('d1').set('linsolver', 'pardiso');
model.sol('sol38').feature('s1').feature('i2').feature('mg1').feature('cs').feature('d1').set('pivotperturb', 1.0E-13);
model.sol('sol38').feature('s1').feature('d1').label('Direct, concentrations (tds)');
model.sol('sol38').feature('s1').feature('d1').set('linsolver', 'pardiso');
model.sol('sol38').feature('s1').feature('d1').set('pivotperturb', 1.0E-13);
model.sol('sol38').feature('s1').feature('d2').label('Direct, concentrations (tds4)');
model.sol('sol38').feature('s1').feature('d2').set('linsolver', 'pardiso');
model.sol('sol38').feature('s1').feature('d2').set('pivotperturb', 1.0E-13);
model.sol('sol38').runAll;

model.result.dataset('cln2').label('Organoid Midline X Axis');
model.result.dataset('cln2').set('genpoints', {'-r_org+0.00175' '0' 'r_org+h_org'; 'r_org+0.00175' '0' 'r_org+h_org'});
model.result.dataset('cln3').label('Organoid Midline Y Axis');
model.result.dataset('cln3').set('genpoints', {'1.75' '-r_org' 'r_org+h_org'; '1.75' 'r_org' 'r_org+h_org'});
model.result.dataset('cln3').set('spacevars', {'cln2x'});
model.result.dataset('cln4').label('Organoid Midline Z Axis');
model.result.dataset('cln4').set('genpoints', {'1.75' '0' 'h_org'; '1.75' '0' '2*r_org+h_org'});
model.result.dataset('cln4').set('spacevars', {'cln2x'});
model.result.numerical('int1').label('Surface Integration For Partition Coefficient');
model.result.numerical('int1').set('expr', {'v_spr*(genext2(c_PDMS)/K_p-c_media)' 'v_spr*(genext1(c_media)-c_PDMS/K_p)'});
model.result.numerical('int1').set('unit', {'mol/s' 'mol/s'});
model.result.numerical('int1').set('descr', {'' ''});
model.result.numerical('gev1').label('Simulated Percent Hypoxia');
model.result.numerical('gev1').set('expr', {'intop1(c<=c_hypox)/intop1(1)'});
model.result.numerical('gev1').set('unit', {'1'});
model.result.numerical('gev1').set('descr', {''});
model.result('pg4').label('Concentration, Whole Device');
model.result('pg4').set('looplevel', [5]);
model.result('pg4').set('titletype', 'custom');
model.result('pg4').set('typeintitle', false);
model.result('pg4').feature('slc1').set('quickplane', 'zx');
model.result('pg4').feature('slc1').set('quickynumber', 1);
model.result('pg4').feature('slc1').set('interactive', true);
model.result('pg4').feature('slc1').set('resolution', 'normal');
model.result('pg4').feature('slc2').set('quickplane', 'zx');
model.result('pg4').feature('slc2').set('quickynumber', 1);
model.result('pg4').feature('slc2').set('interactive', true);
model.result('pg4').feature('slc2').set('resolution', 'normal');
model.result('pg19').label('Concentration Midlines Through Organoid');
model.result('pg19').set('data', 'cln2');
model.result('pg19').set('xlabel', 'X-coordinate (mm)');
model.result('pg19').set('xlabelactive', true);
model.result('pg19').set('ylabel', 'O2 Concentration (mM)');
model.result('pg19').set('ylabelactive', true);
model.result('pg19').feature('lngr1').set('resolution', 'normal');
model.result('pg19').feature('lngr2').set('data', 'cln3');
model.result('pg19').feature('lngr2').set('resolution', 'normal');
model.result('pg19').feature('lngr3').set('data', 'cln4');
model.result('pg19').feature('lngr3').set('resolution', 'normal');
model.result('pg20').label('Heaviside Function');
model.result('pg20').set('data', 'cln2');
model.result('pg20').set('xlabel', 'Arc length (mm)');
model.result('pg20').set('ylabel', 'flc2hs(c/c_hypox-1,0.5) (1)');
model.result('pg20').set('xlabelactive', false);
model.result('pg20').set('ylabelactive', false);
model.result('pg20').feature('lngr1').set('resolution', 'normal');
model.result('pg20').feature('lngr2').active(false);
model.result('pg20').feature('lngr2').set('data', 'cln3');
model.result('pg20').feature('lngr2').set('resolution', 'normal');
model.result('pg23').label('Concentration, Streamlines');
model.result('pg23').set('titletype', 'custom');
model.result('pg23').feature('str1').set('expr', {'tds4.tflux_c_mediax' 'tds4.tflux_c_mediay' 'tds4.tflux_c_mediaz'});
model.result('pg23').feature('str1').set('posmethod', 'uniform');
model.result('pg23').feature('str1').set('linetype', 'tube');
model.result('pg23').feature('str1').set('tuberadiusscale', 0.10000000000000003);
model.result('pg23').feature('str1').set('pointtype', 'arrow');
model.result('pg23').feature('str1').set('arrowcount', 32);
model.result('pg23').feature('str1').set('arrowlength', 'logarithmic');
model.result('pg23').feature('str1').set('arrowscale', 6.557776822756012E7);
model.result('pg23').feature('str1').set('tuberadiusscaleactive', false);
model.result('pg23').feature('str1').set('arrowcountactive', false);
model.result('pg23').feature('str1').set('arrowscaleactive', false);
model.result('pg23').feature('str1').set('resolution', 'normal');
model.result('pg23').feature('str1').feature('col').set('titletype', 'custom');
model.result('pg23').feature('str1').feature('col').set('rangecoloractive', true);
model.result('pg23').feature('str1').feature('col').set('rangecolormin', 0.05);
model.result('pg23').feature('str1').feature('col').set('rangecolormax', 0.2);
model.result('pg23').feature('str2').set('posmethod', 'uniform');
model.result('pg23').feature('str2').set('linetype', 'tube');
model.result('pg23').feature('str2').set('tuberadiusscale', 0.10000000000000003);
model.result('pg23').feature('str2').set('pointtype', 'arrow');
model.result('pg23').feature('str2').set('arrowcount', 50);
model.result('pg23').feature('str2').set('arrowlength', 'logarithmic');
model.result('pg23').feature('str2').set('arrowscale', 6.973596621522813E7);
model.result('pg23').feature('str2').set('tuberadiusscaleactive', false);
model.result('pg23').feature('str2').set('arrowcountactive', false);
model.result('pg23').feature('str2').set('arrowscaleactive', false);
model.result('pg23').feature('str2').set('resolution', 'normal');
model.result('pg23').feature('str2').feature('col').set('descr', 'Concentration');
model.result('pg23').feature('str2').feature('col').set('titletype', 'custom');
model.result('pg23').feature('str2').feature('col').set('rangecoloractive', true);
model.result('pg23').feature('str2').feature('col').set('rangecolormin', 1.0254807033895952);
model.result('pg23').feature('str2').feature('col').set('rangecolormax', 1.5);
model.result('pg24').label('Concentration, Organoid Only');
model.result('pg24').set('titletype', 'custom');
model.result('pg24').set('typeintitle', false);
model.result('pg24').set('edges', false);
model.result('pg24').feature('slc1').set('quickxnumber', 1);
model.result('pg24').feature('slc1').set('interactive', true);
model.result('pg24').feature('slc1').set('rangecoloractive', true);
model.result('pg24').feature('slc1').set('rangecolormin', 0.05);
model.result('pg24').feature('slc1').set('rangecolormax', 0.2);
model.result('pg24').feature('slc1').set('resolution', 'normal');
model.result.export('img3').label('YZ Static');
model.result.export('img3').set('unit', 'px');
model.result.export('img3').set('lockratio', false);
model.result.export('img3').set('width', 1200);
model.result.export('img3').set('height', 1200);
model.result.export('img3').set('sizedesc', '51 x 51 mm');
model.result.export('img3').set('pngfilename', '/home1/eichenba/Downloads/Static/yzStatic.png');
model.result.export('img3').set('alwaysask', true);
model.result.export('img3').set('size', 'manualweb');
model.result.export('img3').set('unit', 'px');
model.result.export('img3').set('height', '1200');
model.result.export('img3').set('width', '1200');
model.result.export('img3').set('lockratio', 'off');
model.result.export('img3').set('resolution', '600');
model.result.export('img3').set('antialias', 'on');
model.result.export('img3').set('zoomextents', 'on');
model.result.export('img3').set('fontsize', '16');
model.result.export('img3').set('colortheme', 'globaltheme');
model.result.export('img3').set('customcolor', [1 1 1]);
model.result.export('img3').set('background', 'current');
model.result.export('img3').set('gltfincludelines', 'on');
model.result.export('img3').set('title1d', 'on');
model.result.export('img3').set('legend1d', 'on');
model.result.export('img3').set('logo1d', 'on');
model.result.export('img3').set('options1d', 'on');
model.result.export('img3').set('title2d', 'on');
model.result.export('img3').set('legend2d', 'on');
model.result.export('img3').set('logo2d', 'on');
model.result.export('img3').set('options2d', 'off');
model.result.export('img3').set('title3d', 'off');
model.result.export('img3').set('legend3d', 'off');
model.result.export('img3').set('logo3d', 'off');
model.result.export('img3').set('options3d', 'on');
model.result.export('img3').set('axisorientation', 'off');
model.result.export('img3').set('grid', 'off');
model.result.export('img3').set('axes1d', 'on');
model.result.export('img3').set('axes2d', 'on');
model.result.export('img3').set('showgrid', 'on');
model.result.export('img3').set('target', 'file');
model.result.export('img3').set('qualitylevel', '92');
model.result.export('img3').set('qualityactive', 'off');
model.result.export('img3').set('imagetype', 'png');
model.result.export('img3').set('lockview', 'off');
model.result.export('img4').label('XY Static');
model.result.export('img4').set('unit', 'px');
model.result.export('img4').set('lockratio', false);
model.result.export('img4').set('width', 1200);
model.result.export('img4').set('height', 1200);
model.result.export('img4').set('sizedesc', '51 x 51 mm');
model.result.export('img4').set('pngfilename', '/home1/eichenba/Downloads/Static/xyStatic.png');
model.result.export('img4').set('alwaysask', true);
model.result.export('img4').set('size', 'manualweb');
model.result.export('img4').set('unit', 'px');
model.result.export('img4').set('height', '1200');
model.result.export('img4').set('width', '1200');
model.result.export('img4').set('lockratio', 'off');
model.result.export('img4').set('resolution', '600');
model.result.export('img4').set('antialias', 'on');
model.result.export('img4').set('zoomextents', 'on');
model.result.export('img4').set('fontsize', '16');
model.result.export('img4').set('colortheme', 'globaltheme');
model.result.export('img4').set('customcolor', [1 1 1]);
model.result.export('img4').set('background', 'current');
model.result.export('img4').set('gltfincludelines', 'on');
model.result.export('img4').set('title1d', 'on');
model.result.export('img4').set('legend1d', 'on');
model.result.export('img4').set('logo1d', 'on');
model.result.export('img4').set('options1d', 'on');
model.result.export('img4').set('title2d', 'on');
model.result.export('img4').set('legend2d', 'on');
model.result.export('img4').set('logo2d', 'on');
model.result.export('img4').set('options2d', 'off');
model.result.export('img4').set('title3d', 'off');
model.result.export('img4').set('legend3d', 'off');
model.result.export('img4').set('logo3d', 'off');
model.result.export('img4').set('options3d', 'on');
model.result.export('img4').set('axisorientation', 'off');
model.result.export('img4').set('grid', 'off');
model.result.export('img4').set('axes1d', 'on');
model.result.export('img4').set('axes2d', 'on');
model.result.export('img4').set('showgrid', 'on');
model.result.export('img4').set('target', 'file');
model.result.export('img4').set('qualitylevel', '92');
model.result.export('img4').set('qualityactive', 'off');
model.result.export('img4').set('imagetype', 'png');
model.result.export('img4').set('lockview', 'off');
model.result.export('data1').set('data', 'cln2');
model.result.export('data1').set('expr', {'c'});
model.result.export('data1').set('unit', {'mol/m^3'});
model.result.export('data1').set('descr', {''});
model.result.export('data1').set('filename', '/home1/eichenba/Downloads/StaticXaxis.txt');
model.result.export('data2').set('data', 'cln3');
model.result.export('data2').set('expr', {'c'});
model.result.export('data2').set('unit', {'mol/m^3'});
model.result.export('data2').set('descr', {''});
model.result.export('data2').set('filename', '/home1/eichenba/Downloads/StaticYaxis.txt');
model.result.export('data3').set('data', 'cln3');
model.result.export('data3').set('expr', {'c'});
model.result.export('data3').set('unit', {'mol/m^3'});
model.result.export('data3').set('descr', {''});
model.result.export('data3').set('filename', '/home1/eichenba/Downloads/StaticZaxis.txt');
model.result.export('img5').label('Organoid Concentration Slice');
model.result.export('img5').set('sourceobject', 'pg24');
model.result.export('img5').set('lockratio', false);
model.result.export('img5').set('pngfilename', '/home1/eichenba/Downloads/Static/OrganoidXY.png');
model.result.export('img5').set('alwaysask', true);
model.result.export('img5').set('size', 'manualweb');
model.result.export('img5').set('unit', 'mm');
model.result.export('img5').set('height', '50');
model.result.export('img5').set('width', '50');
model.result.export('img5').set('lockratio', 'off');
model.result.export('img5').set('resolution', '600');
model.result.export('img5').set('antialias', 'on');
model.result.export('img5').set('zoomextents', 'on');
model.result.export('img5').set('fontsize', '16');
model.result.export('img5').set('colortheme', 'globaltheme');
model.result.export('img5').set('customcolor', [1 1 1]);
model.result.export('img5').set('background', 'current');
model.result.export('img5').set('gltfincludelines', 'on');
model.result.export('img5').set('title1d', 'on');
model.result.export('img5').set('legend1d', 'on');
model.result.export('img5').set('logo1d', 'on');
model.result.export('img5').set('options1d', 'on');
model.result.export('img5').set('title2d', 'on');
model.result.export('img5').set('legend2d', 'on');
model.result.export('img5').set('logo2d', 'on');
model.result.export('img5').set('options2d', 'off');
model.result.export('img5').set('title3d', 'off');
model.result.export('img5').set('legend3d', 'off');
model.result.export('img5').set('logo3d', 'off');
model.result.export('img5').set('options3d', 'on');
model.result.export('img5').set('axisorientation', 'off');
model.result.export('img5').set('grid', 'off');
model.result.export('img5').set('axes1d', 'on');
model.result.export('img5').set('axes2d', 'on');
model.result.export('img5').set('showgrid', 'on');
model.result.export('img5').set('target', 'file');
model.result.export('img5').set('qualitylevel', '92');
model.result.export('img5').set('qualityactive', 'off');
model.result.export('img5').set('imagetype', 'png');
model.result.export('img5').set('lockview', 'off');
model.result.export('img6').label('Streamlines');
model.result.export('img6').set('sourceobject', 'pg23');
model.result.export('img6').set('lockratio', false);
model.result.export('img6').set('pngfilename', '/home1/eichenba/Downloads/Static/Streamline.png');
model.result.export('img6').set('size', 'manualweb');
model.result.export('img6').set('unit', 'mm');
model.result.export('img6').set('height', '50');
model.result.export('img6').set('width', '50');
model.result.export('img6').set('lockratio', 'off');
model.result.export('img6').set('resolution', '600');
model.result.export('img6').set('antialias', 'on');
model.result.export('img6').set('zoomextents', 'on');
model.result.export('img6').set('fontsize', '16');
model.result.export('img6').set('colortheme', 'globaltheme');
model.result.export('img6').set('customcolor', [1 1 1]);
model.result.export('img6').set('background', 'current');
model.result.export('img6').set('gltfincludelines', 'on');
model.result.export('img6').set('title1d', 'on');
model.result.export('img6').set('legend1d', 'on');
model.result.export('img6').set('logo1d', 'on');
model.result.export('img6').set('options1d', 'on');
model.result.export('img6').set('title2d', 'on');
model.result.export('img6').set('legend2d', 'on');
model.result.export('img6').set('logo2d', 'on');
model.result.export('img6').set('options2d', 'off');
model.result.export('img6').set('title3d', 'off');
model.result.export('img6').set('legend3d', 'off');
model.result.export('img6').set('logo3d', 'off');
model.result.export('img6').set('options3d', 'on');
model.result.export('img6').set('axisorientation', 'off');
model.result.export('img6').set('grid', 'off');
model.result.export('img6').set('axes1d', 'on');
model.result.export('img6').set('axes2d', 'on');
model.result.export('img6').set('showgrid', 'on');
model.result.export('img6').set('target', 'file');
model.result.export('img6').set('qualitylevel', '92');
model.result.export('img6').set('qualityactive', 'off');
model.result.export('img6').set('imagetype', 'png');
model.result.export('img6').set('lockview', 'off');

out = model;
